server.name: kibana
server.host: "0.0.0.0"
server.basePath: "/kibana"
server.rewriteBasePath: true

#自行設定
server.publicBaseUrl: "${ZTA_DOMAIN}/kibana"
elasticsearch.hosts:
  - "http://elasticsearch:9200"
